"""add deal_alerts table

Revision ID: 52ff9aa3c21c
Revises: 68e1a4c8ed66
Create Date: 2026-03-02 00:55:05.361365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ff9aa3c21c'
down_revision: Union[str, Sequence[str], None] = '68e1a4c8ed66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_alerts_email'), 'deal_alerts', ['email'], unique=False)
    op.create_index(op.f('ix_deal_alerts_id'), 'deal_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_deal_alerts_keyword'), 'deal_alerts', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_alerts_keyword'), table_name='deal_alerts')
    op.drop_index(op.f('ix_deal_alerts_id'), table_name='deal_alerts')
    op.drop_index(op.f('ix_deal_alerts_email'), table_name='deal_alerts')
    op.drop_table('deal_alerts')
    # ### end Alembic commands ###
