"""add likes, comments, is_ended to deal

Revision ID: 68e1a4c8ed66
Revises: 82e2f5d3d156
Create Date: 2026-03-02 00:48:33.547783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e1a4c8ed66'
down_revision: Union[str, Sequence[str], None] = '82e2f5d3d156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('comments', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('is_ended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'is_ended')
    op.drop_column('deals', 'comments')
    op.drop_column('deals', 'likes')
    # ### end Alembic commands ###
